### ISSUE TITLE
qty should be a float

### ISSUE THREAD

**Issue by roman-jaduda** [InteractiveAdvertisingBureau/openrtb#7]
When referencing digital out of home, shouldn't we allow qty to be a float instead of an integer. 

When using data from studies, they might need to break down the number of contacts to something between 0 and 1.

And even modern tracking systems are advanced enough to say, that a user just saw one third of the spot, so this can go into as 0.333 instead of 0 or 1.

**Comment by iantri** [comment]
When I originally added the DOOH support, I didn't realize the reason that there was an actual practical example of non-integer values. I have since learned that it is in fact the norm.. my bad.

I'm going to propose addition of another field to fix this. Can't redefine type of 'qty' without a breaking change.  But, can add another field. 

Stay tuned.

**Comment by jayshao** [comment]
I think this was done - correct?

**Comment by wittjill** [comment]
qtyflt was added
