### ISSUE TITLE
segtax review and field usage mixup concerns

### ISSUE THREAD

**Issue by zaniphrom** [InteractiveAdvertisingBureau/openrtb#97]
# Standardise referencing taxonomies

Based on Open RTB 2.6 "segtax" is an out of date reference. "cattax" has been added to many objects to refer to the list of categories in the Adcom 3.0 spec. It would be better to align/standardise how this centrally managed list of categories is referred to, see cattax usage in here: https://iabtechlab.com/wp-content/uploads/2021/12/OpenRTB-2.6.pdf 

It appears ``data.ext.cattax`` would now be more suitable if needed. 

# Incorrect field usage

Regarding the need for this extension, there seems to be a conflict between this extension and open RTB itself, specifically between the use of data.segement.id and data.segment.value. To me it appears this spec is confused as to what each means. 

- ``data.segment.id`` Specifies the ID of the segment, e.g. "502" 
- ``data.segment.name`` Specifies the name e.g. "JW Player video content taxonomy" 
- ``data.segment.value`` Specifies the data segment value from within the segment e.g. "1234"

Here's an illustrative example to demonstrate how such data passing currently works without the need for "segtax". 

```json
{
  "data":[
    {
      "id":"jwplayer",
      "name":"JW Player RTD Provider",
      "segment":[
        {
          "id":"502",
          "name":"JW Player video content taxonomy",
          "value":"1234"
        }
      ]
    },
    {
      "id":"dap",
      "name":"Akamai Data Activation Platform (DAP)",
      "segment":[
        {
          "id":"503",
          "name":"Akamai Data Activation Platform (DAP) - Buyer Defined Audiences (BDA), Scrambled",
          "value":"abc123"
        },
        {
          "id":"505",
          "name":"Akamai Data Activation Platform (DAP) - Custom Audiences, Reserved 1",
          "value":"def456"
        }
      ]
    }
  ]
}
```

# Questions

- Can someone comment on the apparent misuse of the ``data.segment.id`` instead of ``data.segment.value`` field in this spec and whether this 'segtax' extension achieves what it sets out to achieve if the data.segment.id field already covers this requirement?
- If there is clarity of purpose for each of their fields, can you add an example where all 3 fields would be used together to demonstrate that clarity i.e. ``segment.id``, ``segment.value``, and ``data.ext.segtax``

**Comment by wittjill** [comment]
@patmmccann do you have thoughts on this one?

**Comment by tedean66** [comment]
I have no idea why this is even relavent to a non California id

**Comment by wittjill** [comment]
The working group wanted this to be very specific that it was a segment taxonomy not a category taxonomy.
The seg tax tells you which taxonomy you are using that then the segment.id would be vendor specific identifier for a specified segment.
- segtax = 543 means that you are using cafe media's custom audience taxonomy
- segment.id = abc123 could be cafemedia's id for auto-intenders or for publisher a's custom audience, etc. 

it's important to note that segment.id wouldn't work for the segment taxonomy reference, because it's meant to articulate which taxonomy is being used, not the value within the taxonomy itself.

i'm not sure how segment.value is used today, but the working group decided not to use it so that it could be very clear on the name/use of segtax.

**Comment by patmmccann** [comment]
data.segment.value is not used in the SDA proposal. If a prebid seller is setting the fields, this is an example of it https://docs.prebid.org/features/firstPartyData.html#first-party-data---prebidjs
